basePath: /
consumes:
- application/json
definitions:
  GenericError:
    description: GenericError is a generic error message returned by a server
    properties:
      message:
        type: string
        x-go-name: Message
    type: object
    x-go-package: github.com/endanga/product-service/handlers
  Product:
    description: Product defines the structure for an API product
    properties:
      brand:
        description: the brand for the product
        maxLength: 255
        type: string
        x-go-name: Brand
      code:
        description: the code for this poduct
        maxLength: 255
        type: string
        x-go-name: Code
      id:
        description: the id for the product
        format: int64
        minimum: 1
        type: integer
        x-go-name: ID
      max_count:
        format: int64
        type: integer
        x-go-name: Max_Count
      name:
        description: the description for this poduct
        maxLength: 255
        type: string
        x-go-name: Name
      retail_price:
        description: the retail_price for the product
        format: double
        maximum: 99999999
        minimum: 1000
        type: number
        x-go-name: Retail_Price
      status:
        description: the status for the product
        type: string
        x-go-name: Status
      sub_category:
        description: the sub_category for the product
        maxLength: 255
        type: string
        x-go-name: Sub_Category
    required:
    - code
    - name
    - sub_category
    - brand
    - retail_price
    - status
    type: object
    x-go-package: github.com/endanga/product-service/data
  ValidationError:
    description: ValidationError is a collection of validation error messages
    properties:
      messages:
        items:
          type: string
        type: array
        x-go-name: Messages
    type: object
    x-go-package: github.com/endanga/product-service/handlers
info:
  description: Documentation for Product API
  title: Sepecification of Product API
  version: 1.0.0
paths:
  /products?limit=10&offset=0:
    get:
      description: Return a list of products from the database
      operationId: listProducts
      responses:
        "200":
          $ref: '#/responses/productsResponse'
      tags:
      - product_repo
produces:
- application/json
responses:
  errorResponse:
    description: Generic error message returned as a string
    schema:
      $ref: '#/definitions/GenericError'
  errorValidation:
    description: Validation errors defined as an array of strings
    schema:
      $ref: '#/definitions/ValidationError'
  noContentResponse:
    description: No content is returned by this API endpoint
  productsResponse:
    description: A list of products
    schema:
      items:
        $ref: '#/definitions/Product'
      type: array
schemes:
- http
swagger: "2.0"
